### ISSUE TITLE
Infinite loop on the self.centroids function of Streaming object ?

### ISSUE THREAD

**Issue by paulremondeau** [wearelumenai/distclus4py#3]
OS : Ubuntu 19.10

The command _free_ gives : 

                                        total                 utilisé           libre        partagé     tamp/cache   disponible
Mem:                              16313748     4211324      9844364      301064     2258060        11545160
Partition d'échange:        1705700           0             1705700

I tried to run this script : 

```python
algo = Streaming(mu=mu, sigma=0.1, outRatio=2, outAfter=7,buffer_size=n)
algo.push(dataset[:1])
algo.run(rasync=True)
algo.push(dataset[1:])
print(algo.centroids)
for k in range(10):#monitoring during 1 seconds since algo is running in a asynchronous mode
    print(k)
    print(len(algo.centroids),'centers',end='|')
    print(k)
    time.sleep(0.1)
```

End of logs is : 
[...]
49 centers|3
4
49 centers|4
5

The notebook keeps running.

Please find my notebook attached.

[Plume.zip](https://github.com/wearelumenai/distclus4py/files/4071555/Plume.zip)

**Comment by b3j0f** [comment]
Hello. Can you give me the entire example ?

**Comment by b3j0f** [comment]
Problem identified, I will be back soon with the solution...

**Comment by b3j0f** [comment]
The problem is more complicated than expected... I will keep abreast of the solution when I will get news.

**Comment by b3j0f** [comment]
I solved the problem. You will have to pull the last version of the lib "distclus", then reinstall it in your environment, and finally, reinstall distclus4py.

I work on a lighter process for updating distclus4py.

Tell me if the bug is fixed

**Comment by paulremondeau** [comment]
The bug is fixed, thank you !
