### ISSUE TITLE
lamda(self): cannot be defined in distclus/mcmc.py

### ISSUE THREAD

**Issue by paulremondeau** [wearelumenai/distclus4py#4]
Line 34, lambda is already a python3 keyword. I think the function name must be changed.

---------------

%%time

import time
from distclus import Batch,MCMC

dataset = np.array(dataset)
n = dataset.shape[0]
print('Analyzing',n,'flow measures----')
algo = Batch(MCMC, init_k=80, frame_size=n, b=1., amp=5,max_k = 400,mcmc_iter=100)
algo.run()
algo.push(dataset)
print(len(algo.centroids),'centers',end='|')

------------------

def lambda(self):
             ^
SyntaxError: invalid syntax

**Comment by paulremondeau** [comment]
This example is from the Plumelabs tutorial, MCMC algorithm part. I renamed the function lambd(self) in mcmc.py and it worked.

Actually _import distclus_ is enough to trigger the error

remondeau@remondeau-Legion-Y540-17IRH:~/go/src/distclus4py$ python3
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distclus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/remondeau/go/src/distclus4py/distclus/__init__.py", line 3, in <module>
    from .mcmc import MCMC
  File "/home/remondeau/go/src/distclus4py/distclus/mcmc.py", line 34
    def lambda(self):
             ^
SyntaxError: invalid syntax

**Comment by b3j0f** [comment]
I pushed a bugfix.

Is it ok ?

**Comment by paulremondeau** [comment]
Yes it is working now thank you :)
